[project]
name = "beans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "platformdirs>=4.3.8",
    "usefullog>=0.8.4",
]
